# ----------------------------
# Makefile Options
# ----------------------------

NAME = MBros
ICON = icon.png
DESCRIPTION = "CE C Toolchain Demo"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell "../bin/cedev-config.exe" --makefile)