# ----------------------------
# Makefile Options
# ----------------------------

NAME = MBros
ICON = icon.png
DESCRIPTION = "Mario Bros Arcade game"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz -ffast-math

# ----------------------------

include $(shell "../bin/cedev-config.exe" --makefile)