#ifndef gfx_include_file
#define gfx_include_file

#ifdef __cplusplus
extern "C" {
#endif

#include "global_palette.h"
#define sprites_palette_offset 0
#include "level1_ground.h"
#include "level1_block_bump1.h"
#include "level1_block_bump2.h"
#include "level1_block_bump3.h"
#include "lava_block_bump1.h"
#include "lava_block_bump2.h"
#include "lava_block_bump3.h"
#include "castle_block_bump1.h"
#include "castle_block_bump2.h"
#include "castle_block_bump3.h"
#include "snowy_iced_block_bump1.h"
#include "snowy_iced_block_bump2.h"
#include "snowy_iced_block_bump3.h"
#include "snowy_normal_block_bump1.h"
#include "snowy_normal_block_bump2.h"
#include "snowy_normal_block_bump3.h"
#define compressed_palette_offset 0
#include "bg_pipes.h"
#include "bg_lava.h"
#include "bg_snowy.h"
#include "bg_castle.h"
#include "bg_title.h"
#define rlet_sprites_palette_offset 0
#include "stand_right.h"
#include "walk1_right.h"
#include "walk2_right.h"
#include "walk3_right.h"
#include "jump_right.h"
#include "stand_left.h"
#include "walk1_left.h"
#include "walk2_left.h"
#include "walk3_left.h"
#include "jump_left.h"
#include "dead.h"
#include "pipe_stationary_right.h"
#include "pipe_stationary_left.h"
#include "pow_full.h"
#include "pow_medium.h"
#include "pow_low.h"
#include "coin1.h"
#include "coin2.h"
#include "coin3.h"
#include "coin4.h"
#include "coin5.h"
#include "pipes_block.h"
#include "snowy_normal_block.h"
#include "snowy_iced_block.h"
#include "lava_block.h"
#include "castle_block.h"
#include "spike_walk1_right.h"
#include "spike_walk2_right.h"
#include "spike_walk3_right.h"
#include "spike_upsidedown1_right.h"
#include "spike_walk1_left.h"
#include "spike_walk2_left.h"
#include "spike_walk3_left.h"
#include "spike_upsidedown1_left.h"
#include "crab_walk1_right.h"
#include "crab_walk2_right.h"
#include "crab_walk3_right.h"
#include "crab_upsidedown1_right.h"
#include "crab_walk1_left.h"
#include "crab_walk2_left.h"
#include "crab_walk3_left.h"
#include "crab_upsidedown1_left.h"
#include "crab_walk1_mad_right.h"
#include "crab_walk2_mad_right.h"
#include "crab_walk3_mad_right.h"
#include "crab_walk1_mad_left.h"
#include "crab_walk2_mad_left.h"
#include "crab_walk3_mad_left.h"
#include "fly_ground.h"
#include "fly_wing1.h"
#include "fly_wing2.h"
#include "fly_dead_left.h"
#include "fly_dead_right.h"
#include "fireball_green_big_rot1.h"
#include "fireball_green_big_rot2.h"
#include "fireball_green_big_rot3.h"
#include "fireball_green_big_rot4.h"
#include "fireball_red_big_rot1.h"
#include "fireball_red_big_rot2.h"
#include "fireball_red_big_rot3.h"
#include "fireball_red_big_rot4.h"
#include "phase_card.h"
#include "phase_number0.h"
#include "phase_number1.h"
#include "phase_number2.h"
#include "phase_number3.h"
#include "phase_number4.h"
#include "phase_number5.h"
#include "phase_number6.h"
#include "phase_number7.h"
#include "phase_number8.h"
#include "phase_number9.h"
#include "phase_clear.h"

#ifdef __cplusplus
}
#endif

#endif
